name: Docs

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

env:
    CARGO_TERM_COLOR: always

jobs:
    doc:

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust
              uses: actions-rs/toolchain@v1

            - name: Check documentation
              run: RUSTDOCFLAGS="-D warnings" cargo doc --document-private-items --all --verbose --release

