name: Rustdoc

on:
  push:
    paths:
      - "**/*.rs"
      - "README.md"
      - ".github/workflows/rustdoc.yml"
  pull_request:
    paths:
      - "**/*.rs"
      - "README.md"
      - ".github/workflows/rustdoc.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Check documentation
        run: RUSTDOCFLAGS="-D warnings" cargo doc --document-private-items --all --release
