name: Rust nightly

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Update toolchain
              run: rustup update
            - name: Install nightly
              run: rustup default nightly
            - name: Build
              run: cargo build --release --verbose

    test:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Run tests
              run: cargo test --verbose
