name: Rust nightly

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

env:
    CARGO_TERM_COLOR: always

jobs:
    install:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Update toolchain
              run: rustup update
            - name: Install nightly
              run: rustup default nightly

    check:
        needs: install
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Cargo clippy
              run: cargo clippy --all -- --verbose -W clippy::all -W clippy::pedantic -W clippy::nursery  -W clippy::correctness -W clippy::complexity -W clippy::perf -W clippy::style -W clippy::suspicious -W clippy::restriction -D warnings

    build:
        needs: install
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Cargo build
              run: cargo build --release --verbose

    test:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Run tests
              run: cargo test --verbose

    doc:
        needs: install
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Check doc
              run: cargo doc --document-private-items --all --verbose --release
