name: Tests

on:
  push:
    paths:
      - "**/*.rs"
      - "README.md"
      - ".github/workflows/tests.yml"
  pull_request:
    paths:
      - "**/*.rs"
      - "README.md"
      - ".github/workflows/tests.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - "--features debug"
          - ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Run tests
        run: cargo test ${{ matrix.features }}
