name: Tests

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust
              uses: actions-rs/toolchain@v1

            - name: Run tests
              run: cargo test --verbose

